-- CREATE TABLE products (
--     id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     sku VARCHAR(100) UNIQUE,
--     description TEXT,
--     default_batch_size DECIMAL(10,2),
--     is_active BOOLEAN DEFAULT TRUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
