CREATE TABLE raw_materials (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    material_uuid CHAR(36) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    unit_type_id BIGINT UNSIGNED,
    unit_price DECIMAL(12, 4) NOT NULL,
    is_gst_itc BOOLEAN DEFAULT FALSE,
    gst DECIMAL(12, 4) DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (unit_type_id) REFERENCES units(id),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);