-- CREATE TABLE cost_items (
--     id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
--     category_id BIGINT UNSIGNED NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     unit_type VARCHAR(50),                 -- e.g. "kg", "hour", "unit"
--     default_rate DECIMAL(12,2) DEFAULT 0.00,
--     vendor_id BIGINT UNSIGNED NULL,
--     is_variable BOOLEAN DEFAULT TRUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     is_active BOOLEAN DEFAULT TRUE,
--     FOREIGN KEY (category_id) REFERENCES cost_categories(id)
-- );
