export const BASE_PATH = {
  vendors: "/vendors",
  dashboard: "/dashboard",
  users: "/users",
  products: "/products",
  vendors: "/vendors",
  rawMaterial: "/raw-material",
  labors: "/labors",
  machines: "/machines",
  overheads: "/overheads",
  indirectExpense: "/indirect-expense",
  utilities: "/utilities",
  batches: "/batches",
  projects: "/projects",
  settings: "/settings",
  bom: "/bom",
};
